
delete  from t_agent_activity_rule where 1=1 and `activity_id` = '47'
delete  from t_agent_activity_rule where 1=1 and `activity_id` = '48'
delete  from t_agent_activity_rule where 1=1 and `activity_id` = '49'
delete  from t_agent_activity_rule where 1=1 and `activity_id` = '50'
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1004','Agent In Asia And Oceania','1','0','100','900','1','{"continen":[1],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10004,10504,11004,11504,12004]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1011','Portuguese Super Agent','1','0','100','900','1','{"league":[11],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10012,10512,11012,11512,12012]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1012','Chinese Super League Agent','1','0','100','900','1','{"league":[12],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10016,10516,11016,11516,12016]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1018','Forbidden Area Fox Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1020','Sharp Inside Forward Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1021','Side Knife Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1022','Classical Midfielder Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1023','Shadow Striker Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1024','Midfield Metronome Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1025','Defensive Midfielder Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1026','Offensive Engine Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1027','Offensive And Defensive Hub Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1028','Fast Sideways Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1029','Sidewalk Barrier Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1030','Master Interceptor Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1031','Muscle Wall Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1032','Offensive Back Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1033','Side Road Iron Gate Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1034','Stubborn Goalkeeper Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1035','Attacking Goalkeeper Agent','1','0','100','900','1','{}','[]','[]','[]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1036','Agent For Players 25 And Under','1','0','100','900','1','{"age":[{"<=":25}],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10086,10586,11086,11586,12086]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1037','26-29 Years Old Player Agent','1','0','100','900','1','{"age":[{">=":26},{"<=":29}],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10087,10587,11087,11587,12087]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1038','Agent For Players Over 30','1','0','100','900','1','{"age":[{">=":30}],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10088,10588,11088,11588,12088]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1039','Agent For Players Under 179Cm','1','0','100','900','1','{"height":[{"<=":179}],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10089,10589,11089,11589,12089]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1040','180-185Cm Player Agent','1','0','100','900','1','{"height":[{">=":180},{"<=":185}],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10090,10590,11090,11590,12090]','1');
replace into t_agent_rule(`agent_id`,`agent_name`,`currency_type`,`first_search_consume`,`search_consume`,`search_ten_consume`,`pool_type`,`player_pool`,`add_player`,`minus_player`,`scout_pool`,`probability_id`) values('1041','Agent For Players Over 186Cm','1','0','100','900','1','{"height":[{">=":186}],"filter":[{"rarity":1,"rating_level":[1,2,3]},{"rarity":2,"rating_level":[1,2,3]},{"rarity":3,"rating_level":[1,2,3]},{"rarity":4,"rating_level":[1,2,3]}]}','[]','[]','[10091,10591,11091,11591,12091]','1');

delete  from t_agent_rule where 1=1 and `agent_id` = '2001'
delete  from t_agent_rule where 1=1 and `agent_id` = '2002'
delete  from t_agent_rule where 1=1 and `agent_id` = '2003'
delete  from t_agent_rule where 1=1 and `agent_id` = '2004'
delete  from t_agent_rule where 1=1 and `agent_id` = '2005'
replace into t_agent_combination_rule(`agent_id`,`agent_name`,`combination`) values('2001','National And Regional Theme Agent','[1001,1002,1003,1004]');
replace into t_agent_combination_rule(`agent_id`,`agent_name`,`combination`) values('2002','European League Theme Agent','[1005,1006,1007,1008,1010,1011]');
replace into t_agent_combination_rule(`agent_id`,`agent_name`,`combination`) values('2003','Player Location Theme Agent','[1013,1014,1015,1016]');
replace into t_agent_combination_rule(`agent_id`,`agent_name`,`combination`) values('2004','Player Age Theme Agent','[1036,1037,1038]');
replace into t_agent_combination_rule(`agent_id`,`agent_name`,`combination`) values('2005','Player Height Theme Agent','[1039,1040,1041]');




delete  from t_agent_quality_probability_rule where 1=1 and `id` = '7' and `probability_id` = '1' and `type` = '2' and `star_rarity` = '5' and `rating_level` = '12076'
delete  from t_agent_quality_probability_rule where 1=1 and `id` = '8' and `probability_id` = '1' and `type` = '2' and `star_rarity` = '5' and `rating_level` = '12077'
delete  from t_agent_quality_probability_rule where 1=1 and `id` = '9' and `probability_id` = '1' and `type` = '2' and `star_rarity` = '5' and `rating_level` = '12078'
delete  from t_agent_quality_probability_rule where 1=1 and `id` = '10' and `probability_id` = '1' and `type` = '2' and `star_rarity` = '5' and `rating_level` = '12079'
