replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3111','11','Super Hero','Super Hero','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3112','11','Champion Cup','Champion Cup','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3113','11','Tiger','Tiger','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3114','11','Devil','Devil','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3115','11','Football','Football','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3116','11','T-shirt','T-shirt','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3117','11','Eagle','Eagle','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3118','11','Knock Out','Knock Out','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3119','11','Who We Are','Who We Are','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3120','11','Super Hero','Super Hero','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3121','11','Champion Cup','Champion Cup','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3122','11','Tiger','Tiger','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3123','11','Devil','Devil','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3124','11','Football','Football','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3125','11','T-shirt','T-shirt','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3126','11','Eagle','Eagle','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3127','11','Knock Out','Knock Out','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3128','11','Who We Are','Who We Are','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3129','11','Super Hero','Super Hero','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3130','11','Champion Cup','Champion Cup','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3131','11','Tiger','Tiger','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3132','11','Devil','Devil','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3133','11','Football','Football','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3134','11','T-shirt','T-shirt','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3135','11','Eagle','Eagle','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3136','11','Knock Out','Knock Out','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3137','11','Who We Are','Who We Are','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3138','11','Super Hero','Super Hero','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3139','11','Champion Cup','Champion Cup','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3140','11','Tiger','Tiger','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3141','11','Devil','Devil','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3142','11','Football','Football','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3143','11','T-shirt','T-shirt','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3144','11','Eagle','Eagle','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3145','11','Knock Out','Knock Out','{}','[]','0','0','{}','1');
replace into t_item(`item_id`,`item_type`,`name`,`desc`,`effect`,`output`,`use_type`,`item_price`,`use_condition`,`is_used`) values('3146','11','Who We Are','Who We Are','{}','[]','0','0','{}','1');


