replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2001','Start Counterattack','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, Our team trailed by <b><i><color=#ffa500ff>{2} : {3}</color></i></b> in the first half, After a half-time interval, it\'s time to start a counterattack!','50','0','2',NULL,NULL,NULL,'[7]','[2]',NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2002','Time is running out！','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, after <b><i><color=#ffa500ff>{4}</color></i></b> minutes of the match, the score is still <b><i><color=#ffa500ff>{2} : {3}</color></i></b>. If we don\'t make any effort, we will lose the game！','75','1','1',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2003','Far ahead','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, after <b><i><color=#ffa500ff>{4}</color></i></b> minutes of the match, we are already <b><i><color=#ffa500ff>{3}</color></i></b> goals ahead of the opponent . Let\'s enjoy the rest of the game!','70','4','0',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2004','Last Stand','It\'s been <b><i><color=#ffa500ff>{4}</color></i></b> minutes since the game started and we are <b><i><color=#ffa500ff>{3}</color></i></b> goals trailed by the opponent. We have no way back!','65','0','2',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2005','Dangerous!','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, we are already <b><i><color=#ffa500ff>{3}</color></i></b> goals trailed by the opponent at home. We can\'t let the home fans down and we have to do our best to win the game！','50','0','2',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2006','Home advantage','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, we are already leading by <b><i><color=#ffa500ff>{2}</color></i></b> goals. It\'s easy to win the game now!','70','3','0',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2007','Away game','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>，we are already in the lead by <b><i><color=#ffa500ff>{2}</color></i></b> goals. We should not give any chance to the opponent!','65','2','0',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2008','Key corner kick','It\'s been <b><i><color=#ffa500ff>{4}</color></i></b> minutes since the game started and we still couldn\'t score a goal. This crucial corner kick is such a big opportunity for us to win the game!','70','0','0',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2009','Turning point!','When the game reaches <b><i><color=#ffa500ff>{4}</color></i></b> minutes, we are <b><i><color=#ffa500ff>{3}</color></i></b> goal behind the opponent. Could this penalty kick be the turning point of the game?','65','0','1',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2010','Real Skills','When the game came to <b><i><color=#ffa500ff>{4} </color></i></b> minutes, we got a threatening free kick in front of the opponent\'s penalty area. It\'s time to show our real skills!','70','1','1',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2011','Plagued By Fouls','When the game went to <b><i><color=#ffa500ff>{4}</color></i></b> minutes, we had two teammates getting yellow cards and one teammate getting a red card. Could we win the game after being plagued by fouls?','60','1','0',NULL,NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2012','Easy Game','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, our team leads the opponent by a score of <b><i><color=#ffa500ff>{2} : {3}</color></i></b> in the first half.  Nothing can stop us from taking the game!','50','2','0','[9,10]','[1,1]',NULL,NULL,NULL,NULL);

