


replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('5','10','9','12','5','0','5001','{"itemAwards":[{"itemId":20042,"num":1},{"itemId":502,"num":5},{"itemId":808,"num":1}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('9','10','9','29','5','0','5001','{"itemAwards":[{"itemId":20040,"num":1},{"itemId":502,"num":5},{"itemId":602,"num":2}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('11','10','10','8','5','0','5002','{"itemAwards":[{"itemId":20030,"num":1},{"itemId":502,"num":5},{"itemId":602,"num":2}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('14','10','10','19','5','0','5002','{"itemAwards":[{"itemId":20047,"num":1},{"itemId":502,"num":5},{"itemId":602,"num":2}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('17','10','11','1','5','0','5002','{"itemAwards":[{"itemId":20049,"num":1},{"itemId":502,"num":5},{"itemId":601,"num":2}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('22','10','11','18','5','0','5002','{"itemAwards":[{"itemId":20055,"num":1},{"itemId":502,"num":5},{"itemId":602,"num":2}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('25','10','12','2','5','0','5003','{"itemAwards":[{"itemId":20056,"num":1},{"itemId":502,"num":5},{"itemId":601,"num":2}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('29','10','12','15','5','0','5003','{"itemAwards":[{"itemId":20057,"num":1},{"itemId":502,"num":5},{"itemId":602,"num":2}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('34','10','13','6','5','0','5003','{"itemAwards":[{"itemId":20058,"num":1},{"itemId":502,"num":5},{"itemId":602,"num":2}]}','0');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('6','10','9','15','1','3','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','820');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('7','10','9','21','1','4','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":602,"num":2}]}','820');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('8','10','9','27','2','5','2002','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','820');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('10','10','10','2','1','6','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','830');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('12','10','10','10','2','7','2008','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','830');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('15','10','10','24','1','8','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','840');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('16','10','10','30','1','9','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":602,"num":2}]}','840');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('19','10','11','7','2','10','2002','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":602,"num":2}]}','850');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('20','10','11','12','1','11','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','850');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('23','10','11','21','2','12','2003','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','860');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('24','10','11','27','1','13','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":602,"num":2}]}','860');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('26','10','12','6','2','14','2012','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":602,"num":2}]}','860');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('28','10','12','12','1','15','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','860');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('30','10','12','22','1','16','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','870');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('32','10','12','29','2','17','2004','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":602,"num":2}]}','870');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('33','10','13','5','1','18','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','870');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('35','10','13','8','1','19','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','880');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('36','10','13','13','2','20','2005','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":602,"num":2}]}','880');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('38','10','13','16','2','21','2010','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":601,"num":2}]}','1000');
replace into t_league_game_schedule_rule(`seq`,`league_id`,`month`,`day`,`schedule_type`,`round`,`sub_id`,`award`,`award_exp`) values('39','10','13','18','1','22','0','{"itemAwards":[{"itemId":2,"num":1000},{"itemId":501,"num":5},{"itemId":602,"num":2}]}','1000');


replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2001','Start Counterattack','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>,Our team lagged behind at <b><i><color=#ffa500ff>{2} : {3}</color></i></b> in the first half,After a half-time interval, it\'s time to launch a counterattack!','45','0','2',NULL,NULL,NULL,'[7]','[2]');
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2002','Already 75 minutes, make effort!','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, after <b><i><color=#ffa500ff>{4}</color></i></b> minutes of the match, we fight with the opponent until <b><i><color=#ffa500ff>{2} : {3}</color></i></b>. If we don\'t make any effort, the game will be suspended!','75','1','1',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2003','Far ahead','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, after <b><i><color=#ffa500ff>{4}</color></i></b> minutes of the match, we are already ahead of the opponent <b><i><color=#ffa500ff>{3}</color></i></b> goals. Let\'s enjoy the rest of the game!','70','4','0',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2004','Last Stand','The game has passed <b><i><color=#ffa500ff>{0}</color></i></b> minutes and we are <b><i><color=#ffa500ff>{3}</color></i></b> goals behind the opponent. We have no retreat! We can only go all out!','65','0','2',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2005','At home, Dangerous!','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, we are already behind the opponent\'s <b><i><color=#ffa500ff>{3}</color></i></b> goals at home. Whether we can keep 
the 3 points at home depends on the last <b><i><color=#ffa500ff>{5}</color></i></b> of the game!','50','0','2',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2006','At home, take it!','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>, we are already ahead <b><i><color=#ffa500ff>{2}</color></i></b> goals. It\'s easy to win 3 points now!','70','3','0',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2007','Away points','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>，We are the first to take the lead in <b><i><color=#ffa500ff>{2}</color></i></b> goals , keep the momentum and strive to score 3 points!','65','2','0',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2008','Key corner','The game progressed to <b><i><color=#ffa500ff>{4}</color></i></b> from the start of the game, and we still did not open the situation and we got a key corner kick. Whether we can win the game depends on this opportunity!','78','0','0',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2009','Turning point!','When the game progressed to <b><i><color=#ffa500ff>{4}</color></i></b>, we are behind the opponent <b><i><color=#ffa500ff>{3}</color></i></b> goals and we got a penalty kick. 
Could this be a turning point in the game?','65','1','2',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2010','Real Skills','When the game progressed to <b><i><color=#ffa500ff>{4} </color></i></b>minutes, we got a threatening free kick at the front of the opponent\'s penalty area. It was time to show our real skills!','70','1','1',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2011','Plagued By Fouls','When the game progressed to <b><i><color=#ffa500ff>{4}</color></i></b> minutes，two of us got the yellow card and one got the red card. Can we, who are plagued by fouls, hold the temporary lead?','60','1','0',NULL,NULL,NULL,NULL,NULL);
replace into t_league_special_game_rule(`id`,`title`,`desc`,`begin_time`,`score`,`other_score`,`players`,`player_goals`,`player_time`,`other_players`,`other_goals`,`other_time`) values('2012','Easy Game','In the <b><i><color=#ffa500ff>{0}</color></i></b> against the <b><i><color=#ffa500ff>{1}</color></i></b>,Our team leads the opponent by a score of <b><i><color=#ffa500ff>{2} : {3}</color></i></b> in the first half,After a half-time interval, it\'s time to take over this game!','45','2','0','[9,10]','[1,1]',NULL,NULL,NULL);


replace into t_league_skill_challenge_rule(`skill_challenge_type_id`,`skill_challenge_type_name`,`discribe`,`point1`,`point2`,`point3`,`award1`,`award2`,`award3`) values('3001','Dribble Skills Challenge','Control the player to dribble through the cone on the training ground.\nPlayers with high <b><i><color=#ffa500ff>Dribbling</color></i></b> and <b><i><color=#ffa500ff>Speed </color></i></b>properties can perform better in challenge.');
replace into t_league_skill_challenge_rule(`skill_challenge_type_id`,`skill_challenge_type_name`,`discribe`,`point1`,`point2`,`point3`,`award1`,`award2`,`award3`) values('3002','Free Kick Skills Challenge','Complete free kick shooting challenges in different positions.\nPlayers with high <b><i><color=#ffa500ff>Finishing</color></i></b> and <b><i><color=#ffa500ff>Place_Kicking</color></i></b> properties can perform better in challenge.');
replace into t_league_skill_challenge_rule(`skill_challenge_type_id`,`skill_challenge_type_name`,`discribe`,`point1`,`point2`,`point3`,`award1`,`award2`,`award3`) values('3003','Penalty Kick Skills Challenge','Facing the enemy at 12 yards, complete 8 penalty kicks.\nPlayers with high <b><i><color=#ffa500ff>Finishing</color></i></b> and <b><i><color=#ffa500ff>Kicking_Power</color></i></b> properties can perform better in challenge.');
replace into t_league_skill_challenge_rule(`skill_challenge_type_id`,`skill_challenge_type_name`,`discribe`,`point1`,`point2`,`point3`,`award1`,`award2`,`award3`) values('3004','Penalty Save Skills Challenge','Facing the opponent\'s penalty, observe and choose the direction to save.\nPlayers with high <b><i><color=#ffa500ff>GK_Reflexes</color></i></b> property and <b><i><color=#ffa500ff>Penalty Saver</color></i></b> skill are more dominant in penalty save.');
replace into t_league_skill_challenge_rule(`skill_challenge_type_id`,`skill_challenge_type_name`,`discribe`,`point1`,`point2`,`point3`,`award1`,`award2`,`award3`) values('3005','Corner Kick Skills Challenge','After a corner kick,Scramble for the header and finish the goal.\nPlayers with high <b><i><color=#ffa500ff>Heading</color></i></b> and <b><i><color=#ffa500ff>Lofted_Pass</color></i></b> properties can perform better in challenge.');
replace into t_league_skill_challenge_rule(`skill_challenge_type_id`,`skill_challenge_type_name`,`discribe`,`point1`,`point2`,`point3`,`award1`,`award2`,`award3`) values('3006','Long Range Shot Skills Challenge','Complete a long range shot to score a goal in the specified area.\nPlayers with high <b><i><color=#ffa500ff>Finishing</color></i></b> property and <b><i><color=#ffa500ff>Long Range Shot </color></i></b>skill can raise the threat of long range shots.');
replace into t_league_skill_challenge_rule(`skill_challenge_type_id`,`skill_challenge_type_name`,`discribe`,`point1`,`point2`,`point3`,`award1`,`award2`,`award3`) values('3007','Slide Tackle Skills Challenge','Steal the opponent\'s ball with a tackle,pay attention to avoid fouling!\nPlayers with high <b><i><color=#ffa500ff>Ball_Winning</color></i></b> property 
can improve the accuracy of tackles.');
replace into t_league_skill_challenge_rule(`skill_challenge_type_id`,`skill_challenge_type_name`,`discribe`,`point1`,`point2`,`point3`,`award1`,`award2`,`award3`) values('3008','Pass Skills Challenge','Pass the ball to your teammates, be careful to bypass the defenders.\nPlayers with high <b><i><color=#ffa501ff>Passing</color></i></b> and <b><i><color=#ffa501ff>Lofted_Pass</color></i></b> property 
can improve the success rate of passing.');

