replace into t_scout_rule(`item_id`,`category_id`,`professional_area_id`,`scout_star`,`sell`,`category_name`,`professional_area_name`,`player_attributes`,`attributes_condition`) values('10062','4','4','1','10','ability','Ball winning under 70','ball_winning','{"<":60}');
replace into t_scout_rule(`item_id`,`category_id`,`professional_area_id`,`scout_star`,`sell`,`category_name`,`professional_area_name`,`player_attributes`,`attributes_condition`) values('10063','4','5','1','10','ability','Ball winning 70-85','ball_winning','{">=":60,"<=":75}');
replace into t_scout_rule(`item_id`,`category_id`,`professional_area_id`,`scout_star`,`sell`,`category_name`,`professional_area_name`,`player_attributes`,`attributes_condition`) values('10065','4','7','1','10','ability','Free kick below 70','free_kick','{"<":60}');
replace into t_scout_rule(`item_id`,`category_id`,`professional_area_id`,`scout_star`,`sell`,`category_name`,`professional_area_name`,`player_attributes`,`attributes_condition`) values('10066','4','8','1','10','ability','Free kick 70-85','free_kick','{">=":60,"<=":75}');
replace into t_scout_rule(`item_id`,`category_id`,`professional_area_id`,`scout_star`,`sell`,`category_name`,`professional_area_name`,`player_attributes`,`attributes_condition`) values('10068','4','10','1','10','ability','Finishing below 70','finishing','{"<":60}');
replace into t_scout_rule(`item_id`,`category_id`,`professional_area_id`,`scout_star`,`sell`,`category_name`,`professional_area_name`,`player_attributes`,`attributes_condition`) values('10069','4','11','1','10','ability','Finishing 70-85','finishing','{">=":60,"<=":75}');

replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('1','200','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('2','400','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('3','600','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('4','800','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('5','1000','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('6','1200','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('7','1400','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('8','1600','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('9','1800','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('10','2000','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('11','2200','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('12','2400','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('13','2600','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('14','2800','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('15','3000','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('16','3200','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('17','3400','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('18','3600','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('19','3800','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('20','4000','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('21','4200','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('22','4400','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('23','4600','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('24','4800','4');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('1','200','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('2','400','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('3','600','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('4','800','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('5','1000','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('6','1200','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('7','1400','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('8','1600','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('9','1800','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('10','2000','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('11','2200','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('12','2400','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('13','2600','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('14','2800','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('15','3000','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('16','3200','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('17','3400','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('18','3600','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('19','3800','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('20','4000','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('21','4200','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('22','4400','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('23','4600','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('24','4800','3');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('1','200','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('2','400','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('3','600','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('4','800','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('5','1000','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('6','1200','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('7','1400','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('8','1600','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('9','1800','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('10','2000','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('11','2200','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('12','2400','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('13','2600','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('14','2800','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('15','3000','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('16','3200','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('17','3400','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('18','3600','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('19','3800','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('20','4000','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('21','4200','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('22','4400','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('23','4600','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('24','4800','2');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('1','200','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('2','400','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('3','600','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('4','800','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('5','1000','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('6','1200','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('7','1400','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('8','1600','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('9','1800','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('10','2000','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('11','2200','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('12','2400','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('13','2600','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('14','2800','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('15','3000','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('16','3200','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('17','3400','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('18','3600','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('19','3800','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('20','4000','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('21','4200','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('22','4400','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('23','4600','1');
replace into t_scout_star_rate_rule(`search_star`,`currency_num`,`rarity`,`player_rarity_probability`) values('24','4800','1');




